service: pedirPizzas

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http:
          method: post
          path: pedido
